@startuml Activity_user_sheet
title Activity: Список пользователей
start

:Отправить команду боту /user_sheet;

:Показать Список пользователей;
note right
Редактировать пользователя из списка(каждый элемент списка- гиперссылка)
в конце списка выводится предложение создать нового пользоватетя и команда /user_create;
end note
    if (Выбран пользователь для редактирования) then (Да)
        switch (:действия с пользователем)
        case (Изменение настроек пользователя)
            :Открыть настройки пользователя
            [[ActivityDiagramSettingUser.plantuml]];
        case (Удалить пользователя)
            :Подтвердить удаление;
            :Удалить пользователя;
        case (Посмотреть список SS-Config)
            :Показать список SS-Config;
        case (Ничего не выбрано)          
        endswitch
    elseif (Создать нового) then (Да)
        :Создание нового пользователя;
        :Открыть настройки пользователя
        [[ActivityDiagramSettingUser.plantuml]];
    else
        :Ничего не выбрано;
    endif


stop


@enduml