@startuml Activity_setting_user
title Activity: Редактирование пользователя через Telegram-бота
/'переименовать в создание пользователя'/
start

/':Админ вводит /edit_user;'/
repeat
:Бот запрашивает наименование пользователя;
/':имя внутри нашей системы ;'/
:Пользователь вводит Имя;
repeat while (Имя недопустимо?)

repeat
:Бот запрашивает роль;
:Пользователь выбирает роль;
/':администратор пользователь ;'/
repeat while (Роль указана корректно?)
:Сохраняет изменения;
:Создана пригласительная ссылка
:Копировать ссылку


:Бот сообщает "Обновлено ✅";
:Получить ввод пользователя;

stop
@enduml