@startuml
start

:Отправить команду боту /user_sheet;

:Показать Список пользователей;
note right
Редактировать пользователя из списка(каждый элемент списка- гиперссылка)
в конце списка выводится предложение создать нового пользоватетя и команда /user_create;
end note
    if (Выбран пользователь для редактирования) then (Да)
        :Редактирование пользователя;
        if (Редактировать пользователя?) then (Да)
            :Открыть настройки пользователя;
        elseif (Удалить пользователя) then (Да)
            :Подтвердить удаление;
            :Удалить пользователя;
        elseif (Посмотреть список SS-Config) then (Да)
            :Показать список SS-Config;
        else
            :Ничего не выбрано;
        endif
    elseif (Создать нового) then (Да)
        :Создание нового пользователя;
        :Открыть настройки пользователя;
    else
        :Ничего не выбрано;
    endif


stop


@enduml