@startuml Activity_user_sheet
title Activity: Список пользователей
start

:Отправить команду боту /user_sheet;

:Бот выдает список VPN Доступный для данного пользователя;
:В конце списка бот выдает команду "Создать новый VPN";
note right
Редактировать пользователя из списка(каждый элемент списка- гиперссылка)
в конце списка выводится предложение создать нового пользоватетя и команда /user_create;
end note
    if (Выбран пользователь для редактирования) then (Да)
        switch (:действия с пользователем)
        case (Расшарить пригласительную ссылку)
            :Создана пригласительная ссылка;
            :Копировать ссылку;
        case (Изменить роль пользователя)
            repeat
                :Бот запрашивает новый пароль для Пользователя;
                :Пользователь вводит новый пароль;
            repeat while (Представление недопустимо?)
        case (Переименовать пользователя)
            repeat
                :Бот запрашивает новое представление для Пользователя;
                :Пользователь вводит новое представление;
            repeat while (Представление недопустимо?)
            if (пользователь подтверждает переименование) then (Да)
                :Пользователь переименовывается;
            endif
        case (Удалить пользователя)
            :Подтвердить удаление;
            :Удалить пользователя;
        case (Посмотреть список SS-Config)
            :Показать список SS-Config
            [[ActivityDiagramSSconfigSheet.plantuml]];
        case (Ничего не выбрано)          
        endswitch
    elseif (Создать нового) then (Да)
        :Создание нового пользователя;
        :Открыть настройки пользователя
        [[ActivityDiagramSettingUser.plantuml]];
    else
        :Ничего не выбрано;
    endif


stop


@enduml