@startuml
title Activity: Редактирование пользователя через Telegram-бота

start

/':Админ вводит /edit_user;'/
repeat
:Бот запрашивает имя пользователя;
:Пользователь вводит Имя;
repeat while (Имя недопустимо?)

repeat
:Бот запрашивает роль;
:Пользователь выбирает роль;
repeat while (Роль указана корректно?)

repeat
:Бот запрашивает пароль;
:Пользователь вводит пароль;
:Пользователь вводит повторно пароль;
repeat while (Пароль указан корректно?)


:Сохраняет изменения;

:Бот сообщает "Обновлено ✅";
:Получить ввод пользователя;

stop
@enduml