@startuml
title Activity: Создание пользователя через Telegram-бота

start

:Админ вводит /add_user;
:Бот запрашивает логин нового пользователя;
:Админ вводит логин;

:Бот запрашивает пароль;
:Админ вводит пароль;

:Бот запрашивает роль (User / AdministratorVPN);
:Админ выбирает роль;

:Бот проверяет валидность данных;
:Бот отправляет запрос на создание пользователя;

:Сервер создает пользователя;
:Бот сообщает "Пользователь добавлен ✅";


@enduml
