@startuml

actor AdministratorVPN
actor Owner 

Owner --|> AdministratorVPN

rectangle "Edit User" {
AdministratorVPN  -- (View the list of Users)
(View the list of Users) ..> (Create)
(View the list of Users) ..> (Update)
(Update) ..> (Delete)
(Update) ..> (View the list of SS-config)
(Update) ..> (User Setting)
note right of (User Setting)
        Имя, роль, пароль есть но скрыт
    end note
(User Setting) ..> (Setup new settings)
(Create) ..> (Setup new settings)

}
@enduml