@startuml

actor AdministratorVPN
actor Owner 
actor User

Owner --|> AdministratorVPN
AdministratorVPN --|> User

rectangle "Edit User" {
User  -- (View the list of SS-config)
note right of (View the list of SS-config)
        список ограничен правами пользователя
end note
(View the list of SS-config) ..> (Create)
(View the list of SS-config) ..> (Download)
(View the list of SS-config) ..> (Delete)

}
@enduml