@startuml

actor AdministratorVPN
actor Owner 

Owner --|> AdministratorVPN

rectangle "VPN administration" {
AdministratorVPN  -- (View the list of VPN)
    (View the list of VPN) ..> (Create) 
    (View the list of VPN) ..> (Select)
    (View the list of VPN) ..> (Statistic)
    (Select) ..> (Delete)
    (Select) ..> (View the list of Users)
    (Select) ..> (VPN Setting)
    (Select) ..> (View the list of self ssconfig)
    (Select) ..> (Return View the list of VPN)
    note right of (VPN Setting)
        технические настройки: поле IP адрес, порт, User name, пароль есть но скрыт
    end note
    /'вывести как комментарий: Имя VPN, поля IP адрес, порт, User name, пароль есть но скрыт, нельзя посмотреть но можно задать'/
    (Select) ..> (Rename)
    (VPN Setting) ..> (Setup new settings)
    (Create) --> (Create name)
    (Create name) --> (Setup new settings)

}
@enduml